### ISSUE TITLE
cannot transition on close when remove is true

### ISSUE THREAD

**Issue by giladgray** [HubSpot/drop#94]
So I've got a Drop with a slick sliding transition when it's opened and I want to do the same thing in reverse when it's closed. This happens automatically if `remove` option is `false` (as expected, because the Drop is still in the DOM, but if `remove: true` is set then the Drop disappears instantly.

I noticed in the code that it's adding a listener for transitionEnd so it should be easy enough to close the drop after that event fires instead of immediately? Unless I'm doing something wrong?

**Comment by giladgray** [comment]
Relevant styles for this Drop transition:

```css
.drop-open-transitionend {
  // Show our drop while it's open and while the transition is going on
  display: block;
}

.presentation-tools {
  // transition slide in
  transition: margin-left 0.3s ease;
  margin-left: 120%;
}
.drop-after-open .presentation-tools { margin-left: 0; }
```
